PORT: 8080

# Must end in /
API_ENDPOINT: https://example.com/

# Absolute paths
SQLITE_DB_PATH: "/tmp/.local/share/attic/server.db"
STORAGE_PATH: "/tmp/.local/share/attic/storage"

# A RSA PEM PKCS1 private key 
# (generate with the command `gen-key` in the Nix environment)
PRIVATE_KEY: ""