services:

  # traefik:
  #   image: "traefik:v2.5"
  #   container_name: "traefik"
  #   command:
  #     # - "--log.level=DEBUG"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.watch=true"
  #     - "--providers.file.directory=/config"
  #     - "--providers.file.watch=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.web-secure.address=:443"
  #     - "--entrypoints.registry.address=:5050"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "5050:5050"
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "./traefik-config:/config"
  #     - "./users:/users"
  #     - type: volume
  #       source: certificates
  #       target: /certs
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.traefik_https.rule=Host(`dev-services.cntlitho.com`) && PathPrefix(`/traefik/dashboard/`)"
  #     - "traefik.http.routers.traefik_https.tls=true"
  #     - "traefik.http.routers.traefik_https.entrypoints=web-secure"
  #     - "traefik.http.routers.traefik_https.service=api@internal"
  #     - "traefik.http.routers.traefik_https.middlewares=traefik-path,traefik-auth"

  #     - "traefik.http.middlewares.traefik-path.stripprefix.prefixes=/traefik"

  #     - "traefik.http.routers.traefik_api.rule=Host(`dev-services.cntlitho.com`) && PathPrefix(`/api/`)"
  #     - "traefik.http.routers.traefik_api.tls=true"
  #     - "traefik.http.routers.traefik_api.entrypoints=web-secure"
  #     - "traefik.http.routers.traefik_api.service=api@internal"

  #     - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/users"

  # certbot:
  #   build:
  #     context: "certbot/"
  #   container_name: "certbot"
  #   volumes:
  #     - type: volume
  #       source: certificates
  #       target: /certs
  #     - "./traefik-config:/traefik"
  #   secrets:
  #     - cloudflare_token
  #   command: 
  #     - "/run_forever"

  nix-cache:
    build:
      context: "nix-serve/"
    container_name: "nix-serve"
    volumes:
      - type: volume
        source: nix_volume
        target: /nix
      - type: volume
        source: nix_authorized_keys
        target: /home/nix/.ssh
    secrets:
      - nix_secrets
      - cache-priv-key.pem
    ports:
      - "2323:22"
      - "6000:6000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nix-cache.tls=true"
      - "traefik.http.routers.nix-cache.rule=Host(`nix-cache.cntlitho.com`)"
      - "traefik.http.routers.nix-cache.entrypoints=web-secure"
      - "traefik.http.routers.nix-cache.service=nix-cache"
      - "traefik.http.services.nix-cache.loadbalancer.server.port=5000"

volumes:
  certificates:
  nix_volume:
  nix_authorized_keys:

secrets:
#   gitlab_token:
#     file: gitlab_token.txt
#   cloudflare_token:
#     file: cloudflare_token.ini
  nix_secrets:
    file: hostkeys.tgz
  cache-priv-key.pem:
    file: cache-priv-key.pem